FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine AS builder
WORKDIR /source

COPY . ./
RUN dotnet restore MAS.MissionScheduler/*.csproj
RUN dotnet publish MAS.MissionScheduler/*.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:3.0-alpine
WORKDIR /app
COPY --from=builder /source/MAS.MissionScheduler/out .
ENTRYPOINT [ "dotnet", "MAS.MissionScheduler.dll" ]
