FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine AS builder
WORKDIR /source

COPY . ./
RUN dotnet restore MAS.MissionCreator/*.csproj
RUN dotnet publish MAS.MissionCreator/*.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:3.0-alpine
WORKDIR /app
COPY --from=builder /source/MAS.MissionCreator/out .
ENTRYPOINT [ "dotnet", "MAS.MissionCreator.dll" ]

